Repository CarolinaCedro/HacktoberProject, pull requests merged in 2022-10, with the labels that each got.

#5 fix ishue 01 Fixed #1
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: hacktoberfest

#6 Section
  src/App.js
  src/index.css
Labels: hacktoberfest

#9 Forms
  src/App.js
Labels: hacktoberfest

#10 translate
  public/index.html
Labels: hacktoberfest

#15 login css
  public/assets/css/login.css
Labels: hacktoberfest

#18 add files and css config
  public/assets/css/login.css
Labels: good first issue, hacktoberfest

#19 footer h1 update for issue [#13]
  src/App.js
Labels: good first issue, hacktoberfest

#20 label with textarea added for issue [#16]
  src/App.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#21 feat: added input field
  package-lock.json
  src/App.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#22 Structured the files
  package-lock.json
  public/index.html
  src/App.js
  src/Content.js
  src/index.css
  src/loginForm.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 finalizando challenge 01
  src/Challenges/challenge-01.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#24 finalizando challenge 02
  src/Challenges/challenge-02.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#25 challenge 03 finalizado
  src/Challenges/challenge-03.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#26 Techgirl04
  src/CollaboratorContent/index.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#33 Vidal/challenge04
  src/Challenges/Challenge-04.txt
  src/Challenges/challenge-01.html
  src/Challenges/challenge-02.html
  src/Challenges/challenge-03.html
  src/CollaboratorContent/index.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#35 Ajusta responsividade da home para dispositivos móveis
  src/CollaboratorContent/index.jsx
  src/CollaboratorContent/styles.css
  src/Header/styles.css
  src/Mastermind/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#36 Finalizando desafio 01
  src/CollaboratorContent/index.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#37 Finalizado desafio 02
  src/Challenges/challenge-01.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#38 Finalizado desafio 03
  src/Challenges/challenge-02.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#39 Último desafio feito. 04
  src/Challenges/challenge-03.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#40 Desafio 1 concluido
  src/Challenges/challenge-01.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#42 Desafio 3 concluido
  src/Challenges/challenge-03.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#43 Desafio 4 concluido
  src/CollaboratorContent/index.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
